### ISSUE TITLE
Fuzz all

### ISSUE THREAD

**Issue by JustinDrake** [sigp/beacon-fuzz#34]
Is there a way to fuzz everything, as opposed to a filtered target?

**Comment by pventuzelo** [comment]
For the moment, since we are using separate docker per client, it is not directly possible from eth2fuzz cli tool.
Nevertheless, I just added (7f106474baae0d0721f65a095d4d51b02016dba0) some extra commands in the Makefile to get an equivalent.

You can use:
``` sh
# for each client, build the docker and then run all fuzzing targets during 1 hour each 
make fuzz-all 
```

Implementation is here:
https://github.com/sigp/beacon-fuzz/blob/7f106474baae0d0721f65a095d4d51b02016dba0/eth2fuzz/Makefile#L124-L144

**Comment by zedt3ster** [comment]
Hey @JustinDrake - the latest commits on `master` have fixed this (it just takes a significant amount of time since we need to build all 5 dockers!). Can you please take a look before I close this issue?

**Comment by JustinDrake** [comment]
Thanks; `make fuzz-all` and `make fuzz-[X]` seem to work great :)

> we need to build all 5 dockers

Since we're using Docker, could we do some caching somehow to avoid everyone rebuilding?

**Comment by zedt3ster** [comment]
> Since we're using Docker, could we do some caching somehow to avoid everyone rebuilding?

Unfortunately, every user will have to build the images at least once, as we need to make sure we're all targeting the latest version for each client. However, caching is indeed enabled, meaning that all the dependency installations, client repo cloning, and fuzzing engine installation are only done once!

The first time you run `make fuzz-all` or `make fuzz-[X]` will take a lot longer than the subsequent runs :)

I'll close this issue for now if that's ok, feel free to reopen should you have any issues!
