### ISSUE TITLE
Differential fuzzing

### ISSUE THREAD

**Issue by JustinDrake** [sigp/beacon-fuzz#36]
Can I confirm that cross-client differential fuzzing is currently not supported?

**Comment by pventuzelo** [comment]
Hi @JustinDrake, 

Yes, currently we have:
- eth2fuzz: independant fuzzers per client (but with sharing corpora folder)
- eth2diff: Differential execution using client cli debugging tools (pcli, ncli, zcli, etc.)

Next big step is to rework old beaconfuzz to target latest eth2 version and process corpora generated by eth2fuzz into all implementation using FFI.

In the current state, we have a differential fuzzing equivalent since eth2fuzz corpora is shared between fuzzers. But it will not allow detection of logic bugs, only crashes.

**Comment by zedt3ster** [comment]
To add to @pventuzelo's answer: the existing differential fuzzing work is still accessible via the `beacon-fuzz` root folder (see [README.md](https://github.com/sigp/beacon-fuzz/blob/master/README.md) for instructions, though it is not _dockerized_ the same way `eth2duzz` is). Note this it is not currently maintained (targeting an old spec version, `v0.10.1`). 

We've been focusing on panic detection and corpora generation on all major Eth2 clients over the last few weeks, and will be moving onto revamping `beacon-fuzz` into a Rust differential fuzzer starting from next week.

**Comment by zedt3ster** [comment]
Differential fuzzing is now supported for Teku, Lighthouse and Prysm thanks to #55 
Structural differential fuzzing is available on fuzzing targets ending with `-struct`.
